name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build image in ACR
        run: |
          az acr build \
            --registry ryanplatformacr \
            --image ryan-app:${{ github.sha }} \
            ./app

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group rg-ryan-platform-dev \
            --name ryan-platform-aks \
            --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/ryan-app \
          ryan-app=ryanplatformacr.azurecr.io/ryan-app:${{ github.sha }}
